@extends('layouts.app')

@section('content')
    <div class="block block-rounded m-4">
        <div class="block-header block-header-default">
            <h3 class="block-title">
                eChart
            </h3>
        </div>
        <div class="block-content block-content-full">
            <div id="echart-bar" style="height: 400px;"></div> <!-- Container for ECharts -->
        </div>
    </div>

    <div class="block block-rounded m-4">
        <div class="block-header block-header-default">
            <h3 class="block-title">a
                DataTable
            </h3>
        </div>
        {{-- <a href="{{ route('students.create') }}" class="btn btn-primary">Add Student</a> --}}
        <div class="block-content block-content-full">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">
                <div class="row d-none">
                    <div class="col-sm-12 col-md-6">
                        <div class="dataTables_length" id="DataTables_Table_0_length">
                            <label>
                                <select name="DataTables_Table_0_length" aria-controls="DataTables_Table_0"
                                    class="form-select">
                                    <option value="5">5</option>
                                    <option value="10">10</option>
                                    <option value="20">20</option>
                                </select>
                            </label>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        <div id="DataTables_Table_0_filter" class="dataTables_filter">
                            <label>
                                <input type="search" class="form-control" placeholder="Search.."
                                    aria-controls="DataTables_Table_0">
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row dt-row">
                    <div class="col-sm-12">
                        <table
                            class="table table-bordered table-striped table-vcenter js-dataTable-full dataTable no-footer"
                            id="students-table" aria-describedby="DataTables_Table_0_info">
                            <thead>
                                <tr>
                                    {{-- <th class="text-center sorting" style="width: 80px;">#</th> --}}
                                    <th class="sorting">Name</th>
                                    <th class="sorting">Math Grade</th>
                                    <th class="sorting">Science Grade</th>
                                    <th class="sorting">English Grade</th>
                                    <th class="sorting">Spanish Grade</th>
                                    <th class="sorting">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- DataTables will fill this with data via AJAX -->
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-5">
                        <div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite"></div>
                    </div>
                    <div class="col-sm-12 col-md-7">
                        <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate">
                            <ul class="pagination">
                                <!-- Pagination will be dynamically generated by DataTables -->
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        const students = @json($students);
        const names = students.map(student => {
            return student.name.split(' ').map(name => name.charAt(0)).join(''); // Get initials
        });
        const mathGrades = students.map(student => student.math_grade);
        const englishGrades = students.map(student => student.english_grade);
        const spanishGrades = students.map(student => student.spanish_grade);
        const scienceGrades = students.map(student => student.science_grade);

        $(document).ready(function() {
            $('#students-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route('students.index') }}', // AJAX URL
                columns: [{
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'math_grade',
                        name: 'math_grade'
                    },
                    {
                        data: 'science_grade',
                        name: 'science_grade'
                    },
                    {
                        data: 'english_grade',
                        name: 'english_grade'
                    },
                    {
                        data: 'spanish_grade',
                        name: 'spanish_grade'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    }
                ]
            });

            renderGradesChart();
        });

        function renderGradesChart() {
            // Initialize the chart
            const chartDom = document.getElementById('echart-bar');
            const gradesChart = echarts.init(chartDom);

            // Chart configuration
            const option = {
                title: {
                    // text: 'Student Grades',
                    // subtext: 'Grades by subject',
                    left: 'center'
                },
                tooltip: {
                    trigger: 'axis'
                },
                legend: {
                    data: ['Math', 'English', 'Spanish', 'Science'],
                    // top: '5%'
                },
                xAxis: {
                    type: 'category',
                    data: names
                },
                yAxis: {
                    type: 'value',
                    name: 'Grades',
                    min: 0,
                    max: 100
                },
                series: [{
                        name: 'Math',
                        type: 'bar',
                        data: mathGrades,
                        itemStyle: {
                            color: '#ff7f50'
                        }
                    },
                    {
                        name: 'English',
                        type: 'bar',
                        data: englishGrades,
                        itemStyle: {
                            color: '#87cefa'
                        }
                    },
                    {
                        name: 'Spanish',
                        type: 'bar',
                        data: spanishGrades,
                        itemStyle: {
                            color: '#da70d6'
                        }
                    },
                    {
                        name: 'Science',
                        type: 'bar',
                        data: scienceGrades,
                        itemStyle: {
                            color: '#32cd32'
                        }
                    }
                ]
            };

            gradesChart.setOption(option);
        }
    </script>
@endsection
